transformer.wte.weight
transformer.h.0.attn.hyp_curvature
transformer.h.0.attn.qkv.weight
transformer.h.0.attn.proj.weight
transformer.h.0.attn.proj.bias
transformer.h.0.mlp.0.weight
transformer.h.0.mlp.0.bias
transformer.h.0.mlp.2.weight
transformer.h.0.mlp.2.bias
transformer.h.1.attn.hyp_curvature
transformer.h.1.attn.qkv.weight
transformer.h.1.attn.proj.weight
transformer.h.1.attn.proj.bias
transformer.h.1.mlp.0.weight
transformer.h.1.mlp.0.bias
transformer.h.1.mlp.2.weight
transformer.h.1.mlp.2.bias
transformer.h.2.attn.hyp_curvature
transformer.h.2.attn.qkv.weight
transformer.h.2.attn.proj.weight
transformer.h.2.attn.proj.bias
transformer.h.2.mlp.0.weight
transformer.h.2.mlp.0.bias
transformer.h.2.mlp.2.weight
transformer.h.2.mlp.2.bias
transformer.h.3.attn.hyp_curvature
transformer.h.3.attn.qkv.weight
transformer.h.3.attn.proj.weight
transformer.h.3.attn.proj.bias
transformer.h.3.mlp.0.weight
transformer.h.3.mlp.0.bias
transformer.h.3.mlp.2.weight
transformer.h.3.mlp.2.bias
transformer.h.4.attn.hyp_curvature
transformer.h.4.attn.qkv.weight
transformer.h.4.attn.proj.weight
transformer.h.4.attn.proj.bias
transformer.h.4.mlp.0.weight
transformer.h.4.mlp.0.bias
transformer.h.4.mlp.2.weight
transformer.h.4.mlp.2.bias
lm_head.k
lm_head.a
lm_head.z